import {
  IsString, IsOptional, IsEnum, IsNumber, IsBoolean,
  IsInt, MaxLength, Min, Max
} from 'class-validator';
import {
  AccountType, InterestRateType, InterestPayoutFreq,
} from '../../accounting/entities/account.entity';
import {
  CompoundingFreq, PenaltyChargeType, ProductCategory,
} from '../entities/account-product.entity';

export class CreateAccountProductDto {
  // ── productCode is NOT accepted from client — auto-generated by service ──

  @IsString() @MaxLength(100)
  productName: string;

  @IsOptional() @IsString()
  description?: string;

  /** Required on CREATE, ignored on UPDATE (immutable) */
  @IsOptional() @IsEnum(AccountType)
  accountType?: AccountType;

  /** Dynamic sub-type (validated against accountType on service layer) */
  @IsOptional() @IsString() @MaxLength(50)
  accountSubtype?: string;

  @IsOptional() @IsString() @MaxLength(3)
  currency?: string;

  // ── Balance ──────────────────────────────────────────────────────────────
  @IsOptional() @IsNumber() @Min(0)
  minimumOpeningAmount?: number;

  @IsOptional() @IsNumber() @Min(0)
  minimumBalance?: number;

  @IsOptional() @IsNumber() @Min(0)
  maximumBalance?: number;

  // ── Interest ──────────────────────────────────────────────────────────────
  @IsOptional() @IsNumber() @Min(0) @Max(100)
  interestRate?: number;

  @IsOptional() @IsEnum(InterestRateType)
  interestRateType?: InterestRateType;

  @IsOptional() @IsEnum(InterestPayoutFreq)
  interestPayoutFreq?: InterestPayoutFreq;

  @IsOptional() @IsEnum(CompoundingFreq)
  compoundingFreq?: CompoundingFreq;

  @IsOptional() @IsBoolean()
  autoInterestCredit?: boolean;

  @IsOptional() @IsInt() @Min(1) @Max(28)
  creditDayOfMonth?: number;

  @IsOptional() @IsNumber() @Min(0) @Max(5)
  seniorCitizenExtraRate?: number;

  // ── Tenure ────────────────────────────────────────────────────────────────
  @IsOptional() @IsInt() @Min(1)
  minTenureMonths?: number;

  @IsOptional() @IsInt() @Min(1)
  maxTenureMonths?: number;

  @IsOptional() @IsInt() @Min(1)
  defaultTenureMonths?: number;

  // ── Loan ──────────────────────────────────────────────────────────────────
  @IsOptional() @IsNumber() @Min(0)
  minLoanAmount?: number;

  @IsOptional() @IsNumber() @Min(0)
  maxLoanAmount?: number;

  @IsOptional() @IsNumber() @Min(0) @Max(10)
  processingFeePercent?: number;

  @IsOptional() @IsNumber() @Min(0) @Max(10)
  foreclosureChargePercent?: number;

  @IsOptional() @IsNumber() @Min(0) @Max(30)
  penalInterestRate?: number;

  // ── Penalty ───────────────────────────────────────────────────────────────
  @IsOptional() @IsEnum(PenaltyChargeType)
  penaltyChargeType?: PenaltyChargeType;

  @IsOptional() @IsNumber() @Min(0)
  penaltyChargeValue?: number;

  // ── Limits ────────────────────────────────────────────────────────────────
  @IsOptional() @IsNumber() @Min(0)
  dailyWithdrawalLimit?: number;

  @IsOptional() @IsNumber() @Min(0)
  atmDailyLimit?: number;

  @IsOptional() @IsNumber() @Min(0)
  onlineTxnDailyLimit?: number;

  @IsOptional() @IsNumber() @Min(0)
  overdraftLimit?: number;

  // ── Eligibility ───────────────────────────────────────────────────────────
  @IsOptional() @IsBoolean()
  seniorCitizenOnly?: boolean;

  @IsOptional() @IsBoolean()
  nriOnly?: boolean;

  // ── Features ──────────────────────────────────────────────────────────────
  @IsOptional()
  features?: Record<string, any>;
}

export class UpdateAccountProductDto extends CreateAccountProductDto {}
