// src/modules/auth/auth.service.ts

import { 
  Injectable, 
  UnauthorizedException, 
  ForbiddenException, 
  Logger, 
  InternalServerErrorException,
  HttpException,
  BadRequestException
} from "@nestjs/common";
import { JwtService } from "@nestjs/jwt";
import { UsersService } from "../users/users.service";
import * as bcrypt from 'bcrypt';
import { UserEntity } from "../users/entities/user.entity";
import { MoreThan, Repository } from "typeorm";
import { InjectRepository } from "@nestjs/typeorm";
  import * as crypto from 'crypto';
import { ForgotPasswordDto } from "../users/dto/forgot-password.dto";
import { MailService } from "./mail/mail.service";
import { ResetPasswordDto } from "../users/dto/reset-password.dto";
import { SessionService } from "./session/session.service";
import { getErrorMessage } from "../../common/utils/error-handler.util";
import { simplifyUserAgent } from "./session/session-utils";
import { LoginDto } from "./dto/login.dto";


// 🚀 1. Added a strict interface so we don't use 'any'
export interface LoginPayload {
  identifier: string;
  password: string;
}

@Injectable()
export class AuthService {
  private readonly logger = new Logger(AuthService.name);

  constructor(
    private readonly usersService: UsersService,
    private readonly jwtService: JwtService,
    @InjectRepository(UserEntity) 
    private readonly userRepo: Repository<UserEntity>,
  private readonly mailService: MailService,
  private readonly sessionService : SessionService
  ) {}


async login(loginDto: LoginDto, req: any) {
  try {
    const { identifier, password } = loginDto;

    // 🛡️ 1. Fetch user (Omni-search)
    const user = await this.usersService.findByIdentifier(identifier);
    
    // 🛡️ 2. Generic error for security
    if (!user || !user.password) {
      throw new UnauthorizedException('Invalid email/username or password.');
    }

    // 🛡️ 3. Account Status Check
    if (!user.isActive) {
      throw new ForbiddenException('Account deactivated. Please contact your administrator.');
    }

    // 🛡️ 4. Password Verification
    const isMatch = await bcrypt.compare(password, user.password);
    if (!isMatch) {
      throw new UnauthorizedException('Invalid email/username or password.');
    }

    // 🛡️ 5. SESSION MANAGEMENT: Create record in DB
    const userAgent = req.headers['user-agent'] || 'Unknown Device';
    const ipAddress = req.ip || req.connection.remoteAddress || '0.0.0.0';
    const tempHash = `SESS_${user.id}_${Date.now()}`;
    const cleanDeviceName = simplifyUserAgent(userAgent);

    let sessionId: string | null = null;

    try {
      // We await this because we NEED the sessionId for the JWT payload
      const session = await this.sessionService.createSession({
        userId: user.id,
        device: cleanDeviceName,
        ipAddress: ipAddress,
        refreshTokenHash: tempHash,
      });
      sessionId = session.id; // 🚀 Capture the UUID generated by the DB
    } catch (error) {
      this.logger.error(`[SESSION_ERROR]: Failed to record session for ${user.id}: ${getErrorMessage(error)}`);
      // In a strict banking app, you might throw an error here. 
      // For now, we proceed, but Postman blocking will only work if sessionId exists.
    }

    // 🛡️ 6. Audit: Record login timestamp
    this.recordLogin(user.id); 

    // 🛡️ 7. Build the JWT Payload (Injected with sessionId)
    const payload = { 
      sub: user.id, 
      sessionId: sessionId, // 👈 THE KILL SWITCH: JwtStrategy will verify this ID
      username: user.username,
      email: user.email,  
      role: user.role?.role, 
      bankId: user.bankId,
      branchId: user.branchId
    };

    // 🛡️ 8. Return Token & Profile
    return {
      success: true,
      access_token: this.jwtService.sign(payload),
      user: {
        id: user.id,
        username: user.username,
        fullName: `${user.firstName} ${user.lastName}`,
        email: user.email,
        role: user.role?.role,
        roleName: user.role?.name,

        permissions: user.role?.permissions || {},
        
        bankId: user.bankId,
        branchId: user.branchId,
        firstName: user.firstName,
        lastName: user.lastName,
        phoneNumber: user.phoneNumber,
        roleType: user.roleType
      }
    };

  } catch (error) {
    if (error instanceof HttpException) throw error;

    const errorMessage = error instanceof Error ? error.message : String(error);
    // this.logger.error(`[AUTH_SYSTEM_ERROR]: Unexpected failure for ${loginDto?.identifier}. Details: ${errorMessage}`);
    
    throw new InternalServerErrorException('An unexpected error occurred. Please try again later.');
  }
}

  /**
   * High-performance login tracking
   */
  async recordLogin(userId: string): Promise<void> {
    try {
      await this.userRepo.update(userId, { lastLoginAt: new Date() });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      this.logger.error(`Failed to record lastLoginAt for ${userId}: ${errorMessage}`);
    }
  }


async forgotPassword(forgotPasswordDto: ForgotPasswordDto) {
  try {
    const { email } = forgotPasswordDto;
    const user = await this.userRepo.findOne({ where: { email } });

    // 🛡️ Safe Return: Don't crash if user is null
    if (!user) {
      // We still return 201/200 for security, but we don't proceed with the mail logic
      return { message: 'If an account exists, a reset link has been sent.' };
    }

    const token = crypto.randomBytes(32).toString('hex');
    const expires = new Date();
    expires.setHours(expires.getHours() + 1);

    user.resetToken = token;
    user.resetTokenExpires = expires;
    
    await this.userRepo.save(user);

   console.log('--- RESET TOKEN GENERATED ---', token);
console.log(`🎯 Sending email to database value: "${user.email}"`);
   const resetLink = `http://localhost:4200/reset-password?token=${token}`;
    await this.mailService.sendPasswordReset(user.username, resetLink);

    return { message: 'If an account exists, a reset link has been sent.' };
  } catch (error) {
    // This will help you see the REAL error in your terminal
    console.error('--- FORGOT PASSWORD CRASH REPORT ---');
  console.error(error); 
  console.error('-------------------------------------');
    throw new InternalServerErrorException('Error processing request');
  }
}

async resetPassword(resetPasswordDto: ResetPasswordDto) {
  const { token, password } = resetPasswordDto;

  try {
    // 1. Find user with a valid (unexpired) token
    // MoreThan(new Date()) ensures the resetTokenExpires is in the future
    const user = await this.userRepo.findOne({
      where: {
        resetToken: token,
        resetTokenExpires: MoreThan(new Date()),
      },
    });

    // 2. Validation: If no user found, the token is either wrong or expired
    if (!user) {
      throw new BadRequestException('The reset link is invalid or has expired.');
    }

    // 3. Security: Hash the new password
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    // 4. Update User & Clear Security Fields
    // It is CRITICAL to nullify the token so it cannot be used again
    user.password = hashedPassword;
    user.resetToken = null;
    user.resetTokenExpires = null;

    await this.userRepo.save(user);

    return {
      success: true,
      message: 'Password successfully updated. You can now log in with your new credentials.',
    };

  } catch (error) {
    // If it's a known validation error (like BadRequest), rethrow it
    if (error instanceof BadRequestException) {
      throw error;
    }

    // Otherwise, log the system error and throw a generic 500
    console.error('CRITICAL: Password Reset Failure', error);
    throw new InternalServerErrorException('An unexpected error occurred during password reset.');
  }
}
}